### PR TITLE
warning instead of exit

### PR DESCRIPTION
**Pull request by zezo357**
fix for https://github.com/media-kit/media-kit/issues/378

to log a warning instead of exiting the app

### CODE REVIEW

**Comment by alexmercerind** [comment]
Apologies!

I'm not going to endorse code & packages which I did not author or publish.

I have no control over their code-quality or distribution. Thus, I want to have no relations with the projects which seem to associate themselves with package:media_kit, by either having "media_kit" in their name or etc.

Thanks!

**Comment by zezo357** [comment]
> Apologies!
> 
> I'm not going to endorse code & packages which I did not author or publish.
> 
> I have no control over their code-quality or distribution. Thus, I want to have no relations with the projects which seem to associate themselves with package:media_kit, by either having "media_kit" in their name or etc.
> 
> Thanks!

I get what you mean, but packages cannot be Renamed on pub.dev


This is why instead of just crashing the app for the developers a warning does explain that part  so you let them know.

**Comment by zezo357** [comment]
@alexmercerind just to be sure, you don't like the idea of using media_kit in the name of the package if its not related to you correct?

so if renamed the packages to not use media_kit in the name you will be okay with that?

**Comment by zezo357** [comment]
@alexmercerind can you please answer me , so i do a fix for it from my side without conflicting with what you want?

**Comment by AnonymHK** [comment]
It is obvious that the author is an arrogant person, and even reasonable suggestions will not be accepted by him!

**Comment by alexmercerind** [comment]
@AnonymHK

> It is obvious that the author is an arrogant person, and even reasonable suggestions will not be accepted by him!

I've worked on this project for ~months~ years, even late at nights till 5 AM to make it work on all platforms. It's genuinely a selfless work which I've released for free. There's no need to take this for granted, no one is entitled. I've spent my actual time researching, engineering & designing this. I'm extremely glad that sharing this amount of work gets me called an "arrogant".

package:media_kit is already powering some great applications on different platforms world-wide & hoping to meet more demands. Still, I must take some decisions which will influence the overall success of the project.

It's been a journey learning all of this; flutter_audio_desktop -> dart_vlc -> media_kit, to simply power [my hobby music app :)](https://harmonoid.com).

If people provide detailed bug-reports & be courteous, only then I can provided good support, & I truly have in most cases. However, sometimes I do lose my mind, I'm not a marketing expert, my mood changes based on how my day went by or any other event from daily life. I mostly work on package:media_kit in the AM with sleepy eyes. I have a job & I'm also a student.

<hr>

@zezo357 

Below are some of the reasons for the changes:

**1. Credit & recognition**

If you believe, you have enough experience & knowledge of C/C++, native-interop, shared libraries, FFmpeg, libmpv, OpenGL, Direct3D etc., consider building a video player from scratch & then publish it under your name.

This project is simply not collection of Flutter widgets, there are actual technical challenges here, which I had to solve, research & implement. The difficulty level is also very-high, which I believe you already realize. Even cross-compiling dependencies is difficult, forget the actual implementation involved.

Most importantly, this project is not even on my GitHub profile anymore, it's under it's own GitHub organization to encourage public contributions.

On the other hand, you are simply re-publishing package:media_kit with barely any actual advantages, changes or advancements (~2% of package:media_kit's complexity) & wrapper (which is not even good, more on this is covered later) & grinding "free internet points" & gaining cheap publicity.

I have genuinely worked extremely hard here writing separate code for each platform & publishing it to the public for free. Trust me, **credit & recognition for the work that I've done is the least that I deserve**. Believe me, it feels really bad.

**2. Accountability**

package:media_kit uses some great open-source e.g. FFmpeg, mpv, ANGLE to make things work equally well on all platforms. They're excellent projects but like every other piece of software, they have some bugs, which package:media_kit often faced. In these situations, I never complain about these awesome projects or reach-out to FFmpeg or mpv developers asking for their support or time. I resolve issues on my own either by maintaining own patches for mpv or FFmpeg or implementing any other workarounds within project. Similarly, I have some further improvements in mind (in terms of video rendering performance & etc.) & I will be the one to implement them, I don't ask or blame anyone that they already didn't do it etc.

While you simply blame it on package:media_kit in every single issue you face. Please take accountability for the code & package you have published without blaming it on others, if you've decided to do so. If you don't have enough experience about native development or video/audio playback please refrain from maintaining package:flutter_meedu_videoplayer.

Another issue that relates to accountability, is that I can't take liability for the packages that you or anyone else have built & published. From a personal point of view, I don't find it's code-quality good & implementation stable.

If someone publishes a package that has "media_kit" in it, that brings a false impression that I endorse or support it. In case something is found incorrect or any update is required, I won't be able to do it either.

**3. Quality**

Besides all of the actual work I do/did in package:media_kit, I've tried to enforce high code quality by writing adequate unit-tests (for handling issues & regressions) & doing proper reviews for pull-requests (even my own pull-requests). I don't think package:flutter_meedu_videoplayer package does this. This simply brings another layer of abstraction, which introduces more issues (clearly for no reason). It's barely a minor collection of Flutter UI widgets.

To be clear (you must honestly realize), the video controls offered in package:media_kit are already superior to the ones present in package:flutter_meedu_videoplayer. One is free to judge & it is understood that sense of design is subjective, but the design (style & behavior) of video controls in package:media_kit is 1:1 identical to that of YouTube, used by millions of people daily. In overall experience, one can clearly identify the better implementation.

**4. Lack of need**

All features are present within package:media_kit, with a far wider, stable, cleaner, well-tested & stronger API.

This again brings the point of you making use of package:media_kit to just gain publicity. If you are interested in improving the overall state of the video & audio playback for Flutter or package:media_kit project, you would've been more keen on providing patches or pull-requests.

Obviously, this doesn't mean that every PR will be accepted, proper review & unit-tests are necessary. I'm an engineer, if something is bad it is bad, if something is good it is good. I do not sugar-coat things. I can't say wrong as right or ruin implementation to make someone happy (most of the times however, I will myself improve their code or even rewrite from scratch, which is infact what I've done).

In most situations (95%), package:media_kit is already a super set of package:flutter_meedu_videoplayer, you should rather consider deprecating it & suggest users to use the more stable, cleaner, well-tested & stronger API provided directly within package:media_kit for the greater good. If there is some feature that is missing, just raise PR & package:media_kit will meet further demands if you have any for your any end-user product or software.

The better will be to have a package that meets the overall needs & demands of everyone looking for stable video & audio playback in Flutter. And, this is why I started working on package:media_kit.

**5. Future**

At the end of the day, I have a vision & a goal for the work & time that I'm putting here. Let package:media_kit be independent & don't overshadow or steal the credit of the actual implementation which is doing the real work underneath.

I believe this is better for the overall future of the project & the goal that project aims to achieve.

**6. No effect on existing users of package:media_kit**

People which I entertain i.e. direct/in-direct users of package:media_kit are still using the package & project just fine. I aim to meet their demands & make further advancements to improve the existing experience of package:media_kit.

<hr>

Lastly, I'm going to block you two on GitHub, I'm not really interested in explaining things or getting in any conversations further. I don't really care if your point of view changes or not. There are alternative ways e.g. mail to reach me out.

**Pull request closed without merging**
