### PR TITLE
update change logs to prepare release

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
this has to be merged first https://github.com/media-kit/media-kit/pull/647#pullrequestreview-2088298625

### CODE REVIEW

**Comment by yangjuncode** [comment]
would love to have https://github.com/media-kit/media-kit/pull/823 in the new release

**Comment by abdelaziz-mahdy** [comment]
> would love to have https://github.com/media-kit/media-kit/pull/823 in the new release

The reason I didn't merge that pr is that the memory doesn't get released, so it looks like there is a missing disposes

**Comment by yangjuncode** [comment]
> > would love to have #823 in the new release
> 
> The reason I didn't merge that pr is that the memory doesn't get released, so it looks like there is a missing disposes

oops,  hope https://github.com/media-kit/media-kit/issues/776  will be fixed soon.

**Comment by abdelaziz-mahdy** [comment]
> > > would love to have #823 in the new release
> > 
> > 
> > The reason I didn't merge that pr is that the memory doesn't get released, so it looks like there is a missing disposes
> 
> oops, hope #776 will be fixed soon.

fixes for the widgets memory leak got fixed

**Comment by abdelaziz-mahdy** [comment]
@alexmercerind can you release the changes, since i am lost on how its managed, i updated all of the versions and added change logs, and this will release the windows crash fix pr since it crashes on people machine

**Comment by abdelaziz-mahdy** [comment]
@moffatman can review this too, i used melos to manage the packages versions and linking to not forget any package and making sure all are updated 

this is a dry run 
image

will need to merge first before trying to publish

**Review by moffatman — APPROVED** [review]
looks ok. not an expert of melos though

**Comment by abdelaziz-mahdy** [comment]
> looks ok. not an expert of melos though

its a management tool that auto generates `pubspec_overrides.yaml` files to avoid that we add and remove the overrides manually 

and manage publishing to packages that has version changes

**Pull request merged**
