### PR TITLE
Added Player level access to commands `frame-step` and `frame-back-step`

### PR DESCRIPTION
**Pull request by deckerst**

### CODE REVIEW

**Comment by abdelaziz-mahdy** [comment]
Thank you for your contribution, is it possible to add tests for these new methods just to make sure they work in all platforms? and keep track if they break for any reason?

**Comment by deckerst** [comment]
I can add treats, but I've added implementation for the "real" player only, not the web player (which seems to be completely different and probably does not support frame stepping). Is that ok?

**Comment by abdelaziz-mahdy** [comment]
I think in that case it will not be added since it will only confuse people 😅 if the support can be added in both we can expose it , other than that we leave it to people to use the set property 

@alexmercerind is what I am saying correct?

**Comment by deckerst** [comment]
Do you mean calling the MPV command "frame-step" directly from the consumer app?

**Comment by abdelaziz-mahdy** [comment]
Yes you can use it from the player instance 

Check the player type then call it 

Example 
```
If (player is nativeplayer)
{
(player as NativePlayer).setproperty();
}
```
Note I am writing the code on mobile so it's 99% wrong syntax wise

**Comment by deckerst** [comment]
In case others need this, here's what I use in the end:
```dart
    final platform = _instance.platform;
    if (platform is NativePlayer) {
      if (frameCount > 0) {
        await platform.command(['frame-step']);
      } else if (frameCount < 0) {
        await platform.command(['frame-back-step']);
      }
    }
```

**Pull request closed without merging**
