### PR TITLE
testing mpv 23-09-24

### PR DESCRIPTION
**Pull request by isaacy13**

### CODE REVIEW

**Comment by davidkempers** [comment]
What was the outcome of this test? I'm looking to see how I can update to the latest mpv but don't want to waste my time if it's a dead end.

**Comment by isaacy13** [comment]
Truth be told, this and my other MRs to media_kit were accidents. I was trying to merge to my fork.

From what I recall (>2 months ago), everything worked as expected for my usage (even though it was missing some custom media_kit mpv code)

Note you may have to mess around clearing caches to ensure new mpv file is downloaded

CC @davidkempers

**Comment by isaacy13** [comment]
Also worth noting I'm not affiliated with this library. Didn't run any unit tests or any formal testing.

I ended up reverting to media_kit's version of mpv, since it didn't resolve the crashing or deadlock issues I was looking into at the time

**Comment by davidkempers** [comment]
OK cool, thanks for the info. As it turned out libmpv has been upgraded in media_kit and that version now works for what I required (hls encryption).

**Pull request closed without merging**
