### PR TITLE
fix(android): libass font support

### PR DESCRIPTION
**Pull request by alexmercerind**

### CODE REVIEW

**Comment by user1121114685** [comment]
Finally waited for this update，I mentioned this at the beginning, but I pushed a commit by mistake.
https://github.com/media-kit/media-kit/pull/661

**Comment by alexmercerind** [comment]
Thanks a lot. I should've paid attention.

**Comment by user1121114685** [comment]
Can libmpv follow the official update plan of mpv? gpu-net is not an experimental feature now. It is recommended that our libmpv be updated synchronously every time the mpv version is updated.

**Comment by alexmercerind** [comment]
@user1121114685 I would love to use the latest mpv version too.

However, I do not have time. It takes 1-2 hours to cross-compile libmpv for each release & things often break due to changse upstream... CI fails very often. Infact, I won't be able to publish next update without fixing them. If you have time & think you can help us out, please do. You may get in our Discord etc.

Not sure when gpu-next can be used... we still use --vo=libmpv on all platforms except Android.

**Comment by user1121114685** [comment]
https://github.com/user1121114685/libmpv-android-video-build/actions/workflows/build.yaml I am quite radical and may not be conducive to stable releases, but I am willing to contribute if possible.

**Comment by LeeeYudE** [comment]
@user1121114685 I want to play Dolby videos. Native MPV Android platform can use setVo("gpu-next"), but I can't find the corresponding api for media-kit. If you know, please tell me which api to use

**Pull request merged**
