### PR TITLE
Customize controls

### PR DESCRIPTION
**Pull request by zezo357**
#### Added Features:

- `gesturesEnabledWhileControlsVisible`: Enables or disables gesture controls like volume and brightness adjustments when media controls are visible. 

  > Note: This option is ignored when gestures are disabled.

- `seekOnDoubleTapEnabledWhileControlsVisible`: Allows the double-tap to seek feature to work when the media controls are visible.

  > Note: This option is effective only when `seekOnDoubleTap` is true.

- `gestureSensitivity`: Configures the sensitivity level of gestures like volume and brightness adjustments. The higher the value, the less sensitive the gestures will be.

#### Other Changes:

- Updated conditionals for handling gesture sensitivity and state-dependent features.
- Minor code comments and formatting updates.

#### Rationale:

This PR introduces new variables that enhance the user experience by offering more flexible control options. It also allows developers to adjust the sensitivity of the gesture controls. These options are essential for a more tailored media playback experience. 

Please review and let me know if there are any concerns.

### CODE REVIEW

**Comment by zezo357** [comment]
i want to add horizontal drag to seek,  but i cant get it to work will try again

**Comment by zezo357** [comment]
i added the  horizontal drag , but the double tap to seek is messed up due to me changing the logic to one gesture detector to allow the  horizontal drag

any way will check it again tomorrow hopefullly i came up with a fix for it 

also i would like to make it a builder like the volume and brigthness so people can customize it more if they needed

**Comment by zezo357** [comment]
## Features and Improvements

### Gesture Controls
- **Seek gesture on horizontal drags**: Allows users to seek through the video timeline with horizontal drag movements.
- **Configure gestures to work when controls are visible**: Enables gesture controls even when the on-screen controls are visible.
- **Adjust gesture sensitivity separately for vertical and horizontal**: Provides options to adjust the sensitivity of gestures in both dimensions.
- **Show seek overlay on drags**: An overlay can be displayed while seeking, customizable via a builder function.

### Double-Tap Controls
- **Allow double tap seek when controls visible**: Enables the double-tap to seek feature even when controls are visible on the screen.

### UI Fixes
- **Refactor volume/brightness indicators to ignore input**: Solves the issue where the bottom half of the play button was not clickable.

### Utility Features
- **Helper to format Duration as MM:SS string**: A utility function for formatting time durations.
- **Handle drag gesture based on screen side swiped**: Uses a single gesture detector to differentiate between vertical drags based on the side of the screen that is swiped.

**Review by alexmercerind — APPROVED** [review]
LGTM!

Thanks a lot; apologies for delay.

**Pull request merged**
