### PR TITLE
feat: speed up on long press

### PR DESCRIPTION
**Pull request by zezo357**
fixes: https://github.com/media-kit/media-kit/commit/e01d5344135922289d38a709639a686d92d1a531#commitcomment-132285038

### CODE REVIEW

**Review by alexmercerind — APPROVED** [review]
LGTM!

I haven't tried it out, feel free to merge.

**Comment by zezo357** [comment]
I think it needs an indicator, but I don't have an idea for the placement, and the look.


So I will try to add it , if no idea came to me I will merge it like this

**Comment by zezo357** [comment]
i added an indicator, can you try it and let me know if all is good?

**Comment by user1121114685** [comment]
Great feature, thanks.

**Pull request merged**
