### PR TITLE
feat: video_player_media_kit

### PR DESCRIPTION
**Pull request by zezo357**
#### Edit by @alexmercerind:

Adding package:video_player_media_kit to the repository.

package:video_player_media_kit can serve as a "bridge" between package:video_player & package:media_kit.

The package allows package:video_player to use package:media_kit as a backend. Possible use-cases:

- Support for more platforms in package:video_player.
- Support for wider range of video/audio codec(s) & format(s) in package:video_player.

While it is true that package:media_kit has more features & higher-stability in some cases, some users may prefer using existing package:video_player API in their code-base (or in the period of transition, if any). The usage is as simple as:

```dart
void main() {
  // --------------------------------------------------
  // Make sure to add the respective packages to pubspec.yaml. e.g.
  //
  // dependencies:
  //   media_kit_libs_macos_video: any
  //   media_kit_libs_windows_video: any
  //   media_kit_libs_linux: any
  VideoPlayerMediaKit.ensureInitialized(
    macOS: true,
    windows: true,
    linux: true,
  );
  // --------------------------------------------------


  // Use package:video_player normally!
  runApp(MyApp());
}
```

#### Original comment:

Adding video_player_media_kit to the media_kit repository, positioning it as the official video playback platform interface.

### CODE REVIEW

**Comment by alexmercerind** [comment]
@zezo357,

Can you enable ["Allow edits from maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for this pull-request.

There are few changes which I've made. Let's get this over the line & published.

**Comment by zezo357** [comment]
> @zezo357,
> 
> Can you enable ["Allow edits from maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for this pull-request.
> 
> There are few changes which I've made. Let's get this over the line & published.

done enabled

**Review by alexmercerind — APPROVED** [review]
LGTM!

**Review by birros — APPROVED** [review]
LGTM!

Works fine on iOS and macOS.

**Pull request merged**
