### PR TITLE
feat: use darwin default libs

### LINKED ISSUE #321: [Bug Report] `MPV.xcframework` error on case-sensitive disk on macOS
1.1.1 compile failed on case sentitive disk on macos for there are mix using MPV and Mpv and infact the dirname is Mpv.xframeworks
image

### PR DESCRIPTION
**Pull request by birros**
- bump darwin libs to default flavor
- fix #321
- use symlinks for `FRAMEWORK_SEARCH_PATHS`

### CODE REVIEW

**Comment by alexmercerind** [comment]
WIP?

**Comment by birros** [comment]
> WIP?

I've finished my tests. Ready!

**Review by alexmercerind — APPROVED** [review]
LGTM'ing from my end. Please proceed.

**Review by alexmercerind — APPROVED** [review]
Thanks for updating the CHANGELOG(s).

**Pull request merged**
