### PR TITLE
chore: refactor mimalloc import

### PR DESCRIPTION
**Pull request by TheOneWithTheBraid**
Fixes: #357

### CODE REVIEW

**Comment by TheOneWithTheBraid** [comment]
May I kindly ask for review ?

**Comment by alexmercerind** [comment]
Hi @TheOneWithTheBraid, unfortunately this pull-request is not good.

We want to statically link with mimalloc & not depend upon the one from package manager, as it makes things very much distribution specific.

**Comment by TheOneWithTheBraid** [comment]
@alexmercerind I understand your concern, still, I see a couple of issues with the current implementation :

- you already *do* require `mpv` as distribution dependency - it does not change any effort in setup whether to add one or two dependencies since mimalloc is packaged on seriously any distribution and also easily ships on snap
- if someone does not add mimalloc as dependency, it still works - the plugin can also run without mimalloc - this didn't change
- static linking highly increases my application size and prevents from fast security updates provided by distributions
- the current static linking implementation is awful
  - you call CMAKE in CMAKE - without passing any parameters to it
  - in most build environments, this will likely fail
  
While I understand your concern, I do not think the current approach is a sustainable way to further go.

**Comment by TheOneWithTheBraid** [comment]
@alexmercerind could you elaborate why this PR is closed ? The issue addressed here is still present. I'm open to solve it differently if you prefer static linking, but simply closing a PR without even acknowledging the issue reported exists is a pretty bad attitude.

Another solution could e.g. be using `include_dir` in CMake rather than calling CMake from CMake.

**Pull request closed without merging**
