### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by alexmercerind**
- feat: `VideoControllerConfiguration.androidAttachSurfaceAfterVideoParameters`
- fix: reset subtitle state/stream
- fix: add `rtp` & `udp` to `protocol_whitelist`
- fix: pass all video attributes to fullscreen route
- fix: unmount `CircularProgressIndicator` if invisible
- fix(web): do not throw `UnsupportedError` w/ `SubtitleTrack.(auto|no)`
- fix(android): `hwdec=auto-safe` w/ `enableHardwareAcceleration=true`

### CODE REVIEW

**Review by birros — APPROVED** [review]
LGTM!

**Comment by alexmercerind** [comment]
Flaky tests...

**Comment by alexmercerind** [comment]
Addresses: https://github.com/media-kit/media-kit/issues/394#issuecomment-1694491967
Addresses: #438
Addresses: #460
Addresses: #472

**Comment by SajadRahimi1** [comment]
Hi
I need to change subtitle configuration when it playing.
currently I use this fixes, but subtitle just change in full screen mode and when I exit full screen subtitle goes to default configuration

**Comment by alexmercerind** [comment]
@SajadRahimi1 

I'm not sure how you're using the current API. Please open a separate ticket or reach out on our Discord.

The fix in this pull-request makes full-screen use the same `SubtitleViewConfiguration` passed in `Video` widget.

**Review by birros — APPROVED** [review]
LGTM!

**Pull request merged**
