### PR TITLE
Improving cmake for windows and linux 

### PR DESCRIPTION
**Pull request by zezo357**
https://github.com/media-kit/media-kit/issues/393 hopefully improving the status of this 

to avoid flutter clean when failed 

the logic now will 
check if archive is found -> check its md5 -> if not correct (will delete it) -> then redownload 
if archive is not found -> download it then check its md5

### CODE REVIEW

**Comment by alexmercerind** [comment]
Interesting. Surely looks cleaner & definitely improved.

One more case that I believe would be good to handle is that:

[At all places] we're only checking if "directory exists or not", a better check would be to check if "directory is empty or not"
https://github.com/media-kit/media-kit/blob/30121e0717157a30e97d6419591c1bd787b07bda/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L89

This is mainly because `make_directory` is invoked instantly & the directory is created:

https://github.com/media-kit/media-kit/blob/30121e0717157a30e97d6419591c1bd787b07bda/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L91

But... the headers & shared libraries etc. are extracted some time afterward (PRE_BUILD), thanks to `add_custom_command`:

If any interruption is made between `make_directory` & `add_custom_command`'s execution, the build will endlessly fail.

https://github.com/media-kit/media-kit/blob/30121e0717157a30e97d6419591c1bd787b07bda/libs/windows/media_kit_libs_windows_video/windows/CMakeLists.txt#L91

<hr>

If one creates an empty `libmpv` or `ANGLE` directory, the build will always fail for no reason (even if the archive exists).

**Comment by zezo357** [comment]
That's a valid point I will check it, hopefully I will come up with a clean solution

If not I will let you know the limition I encountered

Thank you for the review ❤️

**Comment by zezo357** [comment]
done: also tested with angle directory (i deleted all files in it) and it got added again.

**Review by alexmercerind — APPROVED** [review]
LGTM!

This is big improvement & will save project from some false issues.

Feel free to merge.

<hr>

One last feedback from my end is to log something as follows whenever integrity check fails:

```
Please try to run "flutter clean" & build project again.
```

Just quitting after saying "integrity check failed." probably seems bit scary to common Flutter developer.

**Comment by zezo357** [comment]
> LGTM!
> 
> This is big improvement & will save project from some false issues.
> 
> Feel free to merge.
> 
> One last feedback from my end is to log something as follows whenever integrity check fails:
> 
> ```
> Please try to run "flutter clean" & build project again.
> ```
> 
> Just quitting after saying "integrity check failed." probably seems bit scary to common Flutter developer.

i think only `build failed (with the error) and please try to build project again.` is enough 
since if they have internet problem and try to download two files one may fail and the other has no problem
so a rebuild will download the only failed one

**Comment by alexmercerind** [comment]
Good point. I was still thinking based on the old CMake script... now that it deletes existing file & redownloads, it seems all right.

**Review by alexmercerind — APPROVED** [review]
Re- LGTM!

**Comment by zezo357** [comment]
will wait for ci then merge, just to be sure there is nothing i missed.

**Comment by zezo357** [comment]
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

i cant merge btw :) will leave it to you then

**Comment by alexmercerind** [comment]
You must now have the permission!

**Comment by zezo357** [comment]
> You must now have the permission!

yes i do now, thank you

also builds passed so i am merging

**Pull request merged**
